# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2021-2024 Jeffrey H. Johnson
version = 1
SPDX-PackageName = "OpenVi"
SPDX-PackageSupplier = "Jeffrey H. Johnson <johnsonjh.dev@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/johnsonjh/OpenVi"
annotations = []
